# Site settings
title: Alex Blog
SEOTitle: 我的博客 | Alex Blog
header-img: img/ai-newheadpic.jpg
email: 2380087797@qq.com
description: "."
keyword: "Alex, Alex Blog, Linux, Arch, 酷安, 软件, android"
url: "https://alexander-huang.github.io"          # your host, for absolute URL
baseurl: ""      # for example, '/blog' if your blog hosted on 'host/blog'
github_repo: "https://github.com/Alexander-Huang/Alexander-Huang.github.io.git" # you code repository

# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "很抱歉，这里的前方是一方通行，你就乖乖的夹着尾巴耸拉着脑袋返回原点吧！"
sidebar-avatar: /img/pg-accelerator-2.jpg      # use absolute URL, seeing it's used in both `/` and `/about/`



# SNS settings
RSS: false
# weibo_username:     none
zhihu_username:     alex1219-35
github_username:    Alexander-Huang
#facebook_username:  baiying.qiu.7
#jianshu_username:   e71990ada2fd
#twitter_username:   qiubaiying




# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`



# Gems
# from PR#40, to support local preview for Jekyll 3.0
gems: [jekyll-paginate]




# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM                            # use Github Flavored Markdown !important



# 评论系统
# Disqus（https://disqus.com/）
# disqus_username: qiubaiying

# Gitalk
gitalk:
  enable: true    #是否开启Gitalk评论
  clientID: dfc79a73954da66d3787                            #生成的clientID
  clientSecret: 4ef0bb0960e2548ecc856f47fb3fb12eaf967cfa    #生成的clientSecret
  repo: Alexander-Huang.github.io    #仓库名称
  owner: Alexander-Huang    #github用户名
  admin: Alexander-Huang
  distractionFreeMode: true #是否启用类似FB的阴影遮罩


# 统计

# Analytics settings
# Baidu Analytics
ba_track_id: b50bf2b12b5338a1845e33832976fd68

# Google Analytics
ga_track_id: 'UA-90855596-1'            # Format: UA-xxxxxx-xx
ga_domain: qiubaiying.top               # 默认的是 auto, 这里我是自定义了的域名，你如果没有自己的域名，需要改成auto





# Featured Tags
featured-tags: true                     # 是否使用首页标签
featured-condition-size: 1              # 相同标签数量大于这个数，才会出现在首页



# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true



# Friends
friends: [
    {
        title: "我的酷安",
        href: "http://www.coolapk.com/u/1340820"
    },{
        title: "Eros_0125",
        href: "http://orz.dog"
    },{
        title: "チェン(arch大佬)",
        href: "http://blog.origincode.me"
    },{
        title: "OnlyLoveFree(termux大佬)",
        href: "https://nidhoggfgg.github.io"
    },{
        title: "kiriki(ROM大佬)",
        href: "https://blog.kiriki.top"
    },{
        title: "pgs666",
        href: "http://pgs666.kdcloud.xyz"
    },{
        title: "stageguard(反正是大佬就对了)",
        href: "https://stageguard.github.io/"
    },{
        title: "pokon548.5(编程大佬？)",
        href: "https://pokon548.ink/"
    },{
        title: "fear0818(酷安id过于高大上)",
        href: "https://fear0818.github.io/"
    },{
        title: "生来彷徨的人（Linux铺路组重要成员）",
        href: "https://codesjobs.github.io/"
    },{
        title: "John’s blog",
        href: "https://celianlh.github.io"
    }
]

theme: jekyll-theme-architect
